services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/inpeak-db
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_REDIS_HOST=redis
      - SECRET_KEY=your-secret-key-should-be-at-least-32-characters-long
      - REDIRECT_URL=http://localhost:5173
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - inpeak-net

  mysql:
    image: mysql:8.0.36
    environment:
      - MYSQL_DATABASE=inpeak-db
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=verysecret
    ports:
      - "13306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    networks:
      - inpeak-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.2
    ports:
      - "16379:6379"
    networks:
      - inpeak-net

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT_MODE=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=UfGzHqV9TN2HhVrzPiVo6w==
    networks:
      - inpeak-net

networks:
  inpeak-net:

volumes:
  mysql-data:
    name: inpeak-mysql-data

